[package]
name = "reward_distribution"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
published-at = "0x451682db8053eced4e8cd1aa3deb9c52f61c9b34650f536ed9c4c1a58327e329"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "b40cdedf4df6f0deaa4a46c1bf99c57029160202" }

[addresses]
reward_distribution = "0x0"


